DIR=$HOME/dotfiles

source $DIR/zsh/prezto/runcoms/zshrc
source $DIR/zsh/aliases.zsh
source $DIR/zsh/colors.zsh
source $DIR/zsh/prompt.zsh
source $DIR/zsh/env.zsh
source $DIR/zsh/git.zsh
source $DIR/zsh/noglob.zsh
source $DIR/zsh/rm.zsh
source $DIR/zsh/zmv.zsh
source $DIR/zsh/zsh-aliases.zsh

export NVM_DIR="/Users/michael/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
